# SwiftLint Configuration for Shvil

# Paths to include/exclude
included:
  - shvil
  - shvilTests

excluded:
  - .build
  - DerivedData
  - shvil.xcodeproj
  - shvil.xcworkspace

# Rules to enable
opt_in_rules:
  - array_init
  - attributes
  - closure_body_length
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_header
  - first_where
  - force_unwrapping
  - function_default_parameter_at_end
  - identical_operands
  - implicit_return
  - joined_default_parameter
  - last_where
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - nslocalizedstring_key
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - prefixed_toplevel_constant
  - prohibited_interface_builder
  - prohibited_super_call
  - redundant_nil_coalescing
  - redundant_type_annotation
  - required_enum_case
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - static_operator
  - strong_iboutlet
  - switch_case_on_newline
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - xct_specific_matcher
  - yoda_condition

# Rules to disable
disabled_rules:
  - todo
  - line_length

# Custom rules
custom_rules:
  no_hardcoded_strings:
    name: "No Hardcoded Strings"
    regex: '"[^"]*"'
    message: "Use localized strings instead of hardcoded strings"
    severity: warning
    excluded:
      - ".*Test.*"
      - ".*Preview.*"

  no_force_unwrapping:
    name: "No Force Unwrapping"
    regex: '!'
    message: "Avoid force unwrapping. Use safe unwrapping instead"
    severity: error
    excluded:
      - ".*Test.*"
      - ".*Preview.*"

  no_print_statements:
    name: "No Print Statements"
    regex: 'print\('
    message: "Use proper logging instead of print statements"
    severity: warning
    excluded:
      - ".*Test.*"
      - ".*Preview.*"

# File header
file_header:
  required_pattern: |
                    \/\/
                    \/\/  .*\.swift
                    \/\/  shvil
                    \/\/
                    \/\/  Created by .* on \d{4}\.
                    \/\/

# Line length
line_length:
  warning: 120
  error: 150
  ignores_urls: true
  ignores_function_declarations: true
  ignores_comments: true

# Function body length
function_body_length:
  warning: 50
  error: 100

# Type body length
type_body_length:
  warning: 300
  error: 500

# File length
file_length:
  warning: 500
  error: 1000

# Cyclomatic complexity
cyclomatic_complexity:
  warning: 10
  error: 20

# Nesting
nesting:
  type_level:
    warning: 3
    error: 6
  statement_level:
    warning: 5
    error: 10

# Identifier name
identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 40
    error: 60
  excluded:
    - id
    - url
    - api
    - ui
    - db

# Type name
type_name:
  min_length:
    warning: 3
    error: 2
  max_length:
    warning: 40
    error: 60

# Trailing whitespace
trailing_whitespace:
  ignores_empty_lines: true

# Vertical whitespace
vertical_whitespace:
  max_empty_lines: 2

# Large tuple
large_tuple:
  warning: 3
  error: 4

# Valid docs
valid_docs:
  requires_fallback: true

# Missing docs
missing_docs:
  warning: [public]
  error: [open]

# Docstring
docstring:
  ignore_private_init: true
